version: '2.1'
# Before running docker-compose, run ./bin/build-docker.sh
services:
  trilium:
    build:
      context: .
    image: zadam/trilium
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - trilium:/home/node/trilium-data

volumes:
  trilium:

