version: '3'
services:
  trilium:
    build:
      context: .
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "9080:8080"
    volumes:
      - /home/oric/Docker/trilium:/data

volumes:
  trilium: