type AttributeInfo = {
    type: "label" | "relation";
    name: string;
    isDangerous?: false;
} | {
    type: "label" | "relation";
    name: string;
    isDangerous: true;
    dangerCategory: "codeExecution" | "serverSideScripting" | "clientSideScripting" | "widget" | "iconPack" | "webview";
};

const builtinAttributes: AttributeInfo[] = [
    // label names
    { type: "label", name: "inbox" },
    { type: "label", name: "disableVersioning" },
    { type: "label", name: "calendarRoot" },
    { type: "label", name: "archived" },
    { type: "label", name: "excludeFromExport" },
    { type: "label", name: "disableInclusion" },
    { type: "label", name: "appCss" },
    { type: "label", name: "appTheme" },
    { type: "label", name: "appThemeBase" },
    { type: "label", name: "hidePromotedAttributes" },
    { type: "label", name: "readOnly" },
    { type: "label", name: "autoReadOnlyDisabled" },
    { type: "label", name: "cssClass" },
    { type: "label", name: "iconClass" },
    { type: "label", name: "keyboardShortcut" },
    { type: "label", name: "run", isDangerous: true, dangerCategory: "codeExecution" },
    { type: "label", name: "runOnInstance", isDangerous: false },
    { type: "label", name: "runAtHour", isDangerous: false },
    { type: "label", name: "customRequestHandler", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "label", name: "customResourceProvider", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "label", name: "widget", isDangerous: true, dangerCategory: "clientSideScripting" },
    { type: "label", name: "noteInfoWidgetDisabled" },
    { type: "label", name: "linkMapWidgetDisabled" },
    { type: "label", name: "revisionsWidgetDisabled" },
    { type: "label", name: "whatLinksHereWidgetDisabled" },
    { type: "label", name: "similarNotesWidgetDisabled" },
    { type: "label", name: "workspace" },
    { type: "label", name: "workspaceIconClass" },
    { type: "label", name: "workspaceTabBackgroundColor" },
    { type: "label", name: "workspaceCalendarRoot" },
    { type: "label", name: "workspaceTemplate" },
    { type: "label", name: "searchHome" },
    { type: "label", name: "workspaceInbox" },
    { type: "label", name: "workspaceSearchHome" },
    { type: "label", name: "sqlConsoleHome" },
    { type: "label", name: "datePattern" },
    { type: "label", name: "weekPattern" },
    { type: "label", name: "enableWeekNote" },
    { type: "label", name: "monthPattern" },
    { type: "label", name: "quarterPattern" },
    { type: "label", name: "yearPattern" },
    { type: "label", name: "enableQuarterNote" },
    { type: "label", name: "pageSize" },
    { type: "label", name: "viewType" },
    { type: "label", name: "mapRootNoteId" },
    { type: "label", name: "mapExcludeRelation" },
    { type: "label", name: "mapIncludeRelation" },
    { type: "label", name: "bookmarkFolder" },
    { type: "label", name: "sorted" },
    { type: "label", name: "sortDirection" },
    { type: "label", name: "sortFoldersFirst" },
    { type: "label", name: "sortNatural" },
    { type: "label", name: "sortLocale" },
    { type: "label", name: "top" },
    { type: "label", name: "bottom" },
    { type: "label", name: "fullContentWidth" },
    { type: "label", name: "shareHiddenFromTree" },
    { type: "label", name: "shareExternalLink" },
    { type: "label", name: "shareAlias" },
    { type: "label", name: "shareOmitDefaultCss" },
    { type: "label", name: "shareRoot" },
    { type: "label", name: "shareDescription" },
    { type: "label", name: "shareRaw" },
    { type: "label", name: "shareDisallowRobotIndexing" },
    { type: "label", name: "shareCredentials" },
    { type: "label", name: "shareIndex" },
    { type: "label", name: "shareHtmlLocation" },
    { type: "label", name: "displayRelations" },
    { type: "label", name: "hideRelations" },
    { type: "label", name: "titleTemplate", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "label", name: "template" },
    { type: "label", name: "toc" },
    { type: "label", name: "color" },
    { type: "label", name: "keepCurrentHoisting" },
    { type: "label", name: "executeButton" },
    { type: "label", name: "executeDescription" },
    { type: "label", name: "newNotesOnTop" },
    { type: "label", name: "clipperInbox" },
    { type: "label", name: "webViewSrc", isDangerous: true, dangerCategory: "webview" },
    { type: "label", name: "hideHighlightWidget" },
    { type: "label", name: "iconPack", isDangerous: true, dangerCategory: "iconPack" },

    { type: "label", name: "printLandscape" },
    { type: "label", name: "printPageSize" },

    // relation names
    { type: "relation", name: "internalLink" },
    { type: "relation", name: "imageLink" },
    { type: "relation", name: "relationMapLink" },
    { type: "relation", name: "includeMapLink" },
    { type: "relation", name: "runOnNoteCreation", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnNoteTitleChange", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnNoteChange", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnNoteContentChange", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnNoteDeletion", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnBranchCreation", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnBranchChange", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnBranchDeletion", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnChildNoteCreation", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnAttributeCreation", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "runOnAttributeChange", isDangerous: true, dangerCategory: "serverSideScripting" },
    { type: "relation", name: "template" },
    { type: "relation", name: "inherit" },
    { type: "relation", name: "widget", isDangerous: true, dangerCategory: "clientSideScripting" },
    { type: "relation", name: "renderNote", isDangerous: true, dangerCategory: "clientSideScripting" },
    { type: "relation", name: "shareCss" },
    { type: "relation", name: "shareJs" },
    { type: "relation", name: "shareHtml" },
    { type: "relation", name: "shareTemplate" },
    { type: "relation", name: "shareFavicon" }
];

export default builtinAttributes;
